cc_binary(
    name = "apue",
    srcs = [
        "iterator.cpp",
    ],
    incs = ["./"],
    deps = [
    ],
    optimize=[
        '-Wno-error=sign-compare',
        '-Wno-error=unused-function',
        '-Wno-error=unused-variable',
    ],  
)
