cc_binary(
  name = "a.out",
  srcs = [
    "",
  ],
  incs = ["./"],
  deps = [
  ],
  optimize=[
    '-Wno-error=sign-compare',
    '-Wno-error=unused-function',
    '-Wno-error=unused-variable',
  ],  
)
