/* rpclist_xdr.c
 *
 * Copyright (c) 2000 Sean Walton and Macmillan Publishers.  Use may be in
 * whole or in part in accordance to the General Public License (GPL).
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
*/

/*****************************************************************************/
/*** rpclist_xdr.c                                                         ***/
/***                                                                       ***/
/*****************************************************************************/

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpclist.h"

bool_t
xdr_TNode (XDR *xdrs, TNode *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct NodeStruct), (xdrproc_t) xdr_NodeStruct))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_NodeStruct (XDR *xdrs, NodeStruct *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->Name, ~0))
		 return FALSE;
	 if (!xdr_TNode (xdrs, &objp->Next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_NodeUnion (XDR *xdrs, NodeUnion *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->Err))
		 return FALSE;
	switch (objp->Err) {
	case 0:
		 if (!xdr_TNode (xdrs, &objp->NodeUnion_u.NameList))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
