/* rpcps_xdr.c
 *
 * Copyright (c) 2000 Sean Walton and Macmillan Publishers.  Use may be in
 * whole or in part in accordance to the General Public License (GPL).
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
*/

/*****************************************************************************/
/*** rpcps_xdr.c                                                           ***/
/***                                                                       ***/
/*****************************************************************************/

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcps.h"

bool_t
xdr_TRow (XDR *xdrs, TRow *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct RowStruct), (xdrproc_t) xdr_RowStruct))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TTable (XDR *xdrs, TTable *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct TableStruct), (xdrproc_t) xdr_TableStruct))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RowStruct (XDR *xdrs, RowStruct *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->Field, ~0))
		 return FALSE;
	 if (!xdr_TRow (xdrs, &objp->Next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TableStruct (XDR *xdrs, TableStruct *objp)
{
	register int32_t *buf;

	 if (!xdr_TRow (xdrs, &objp->Row))
		 return FALSE;
	 if (!xdr_TTable (xdrs, &objp->Next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TableResult (XDR *xdrs, TableResult *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->Err))
		 return FALSE;
	switch (objp->Err) {
	case 0:
		 if (!xdr_TTable (xdrs, &objp->TableResult_u.Table))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
