cc_binary(
  name = "BoostTst",
  srcs = [
      'boost_tst.cpp'
         ],
  incs = ['.'],
  deps = [
      '//thirdparty/boost-1.56.0:boost_system',
      '//thirdparty/boost-1.56.0:boost_date_time',
      '//thirdparty/boost-1.55.0:boost_thread',
      '//thirdparty/boost-1.56.0:boost_regex',
      '//thirdparty/boost-1.56.0:boost_serialization',
      '//thirdparty/boost-1.56.0:boost_system',
      '//thirdparty/boost-1.56.0:boost_filesystem',
      '//thirdparty/boost-1.56.0:boost_program_options',
      '//thirdparty/boost-1.56.0:boost_signals',
      '#pthread',
      '#rt',
         ],
  warning='no',
)


